### ISSUE TITLE
[BUG] Save partitioned parquet dataset using NativeExecutionEngine

### ISSUE THREAD

**Issue by LaurentErreca** [fugue-project/fugue#285]
I failed to execute following command with NativeExecutionEngine:
`SAVE PREPARTITION BY PRODUCT OVERWRITE PARQUET '{{output_path}}'`

I received the following message:

 `partition_spec is not respected in NativeExecutionEngine.save_df`

This should be possible using pandas as function to_parquet when engine='pyarrow' has an argument partition_cols to do the job.
I have quickly tested this:
In file native_execution_engine.py, in function save_df (line 369):
```
 if not partition_spec.empty:
     kwargs['partition_cols'] = partition_spec.partition_by
```

This worked for me.

Cheers,
Laurent

**Environment :**
 - Backend: pandas
 - Backend version: 1.3.5
 - Python version: 3.9.9
 - OS: linux

**Comment by kvnkho** [comment]
@LaurentErreca mentioned on Slack that the above modification fails on the `test_io` test for `NativeExecutionEngine`. The test looks like this:

```python
    def test_io(self):
        path = os.path.join(self.tmpdir, "a")
        path2 = os.path.join(self.tmpdir, "b.test.csv")
        with self.dag() as dag:
            b = dag.df([[6, 1], [2, 7]], "c:int,a:long")
            b.partition(num=3).save(path, fmt="parquet", single=True)
            b.save(path2, header=True)
        assert FileSystem().isfile(path)
```

And it fails in the `assert` statement.

**What does the assert do?**

In this line:
`b.partition(num=3).save(path, fmt="parquet", single=True)`
the `single=True` makes the output a single file.  The assert then checks that the output is a single file.

**Why does it fail?**

Tracing the code a bit, the code path goes like this (but you can ignore the first 2):
* [Workflow DataFrame calls save](https://github.com/fugue-project/fugue/blob/master/fugue/workflow/workflow.py#L1212-L1243). This is the engine-agnostic DAG.
* [It uses the built-in Save processor](https://github.com/fugue-project/fugue/blob/db8b235f104116f299d1ef9719926b00d1366d41/fugue/extensions/_builtins/outputters.py#L78-L96) which uses the appropriate execution engine.
* [NativeExecutionEngine save_df gets called](https://github.com/fugue-project/fugue/blob/master/fugue/execution/native_execution_engine.py#L369-L385)
* [Utils io save_df function](https://github.com/fugue-project/fugue/blob/db8b235f104116f299d1ef9719926b00d1366d41/fugue/_utils/io.py#L97-L120)
* [Save_parquet](https://github.com/fugue-project/fugue/blob/db8b235f104116f299d1ef9719926b00d1366d41/fugue/_utils/io.py#L139-L142)

The issue here is that passing `partition_cols` to the `pandas to_parquet` method created multiple files so it fails the test in the case where `single=True` is passed to the `NativeExecutionEngine`.

**What is the fix?**

From what it looks like, `pandas to_parquet` cannot be forced to a single file if `partition_cols` is provided. It makes sense, because why even provide `partition_cols` if you want a single file. I think in order to pass this test, we need to handle the `single=True` at the Fugue level. If `single=True` when saving the file, ignore the partitioning columns provided. If `single=False`, then we actually use them to output the file. The `NativeExecutionEngine save_df` already takes in the `force_single` [here](https://github.com/fugue-project/fugue/blob/master/fugue/execution/native_execution_engine.py#L376) and it is currently unused so we just need an `if-else` around it. 

Dask actually doesn't have this functionality as well (but Spark does), so the `DaskExecutionEngine` is a good reference [here](https://github.com/fugue-project/fugue/blob/master/fugue_dask/execution_engine.py#L444-L470) because it has that conditional logic based on if `force_single` is `True`. I think the solution might look similar.

**Other considerations**

The `PartitionSpec` takes in `by`, but it can also be defined by using `num`. For example:
```python
from fugue.collections.partition import PartitionSpec
p = PartitionSpec(num=3)
SparkExecutionEngine().save_df(sdf, path, "parquet", "overwrite", p, True)
print(p)
```

and more info can be found [here](https://fugue.readthedocs.io/en/latest/api/fugue.collections.html). It will be quite hard and probably unnecessary to support the use case where the `PartitionSpec` just contains `num`. In this event, I think we should just make an error like [this?](https://github.com/fugue-project/fugue/blob/master/fugue_dask/execution_engine.py#L464-L467) or maybe you can even ignore this case for now and just see if we can do the `if-else` and get those test cases passing.

**Comment by goodwanghan** [comment]
We will try to solve it in https://github.com/fugue-project/fugue/issues/296

**Comment by LaurentErreca** [comment]
Hi,
I have have been working on it, but I'm still having issues with Dask engine as I'm not able to save a hive partitioned parquet dataset. Working on my fork, here : https://github.com/LaurentErreca/fugue/tree/fix/issue_285

**Comment by LaurentErreca** [comment]
When using Dask execution engine, we can use parameter `partition_on` to write hive partitioned dataset. Still working on it in https://github.com/LaurentErreca/fugue/tree/fix/issue_285

**Comment by goodwanghan** [comment]
Hey, @LaurentErreca it seems I have no access to your fork. But it is exciting to see you are working on it. I am looking forward to it!!

**Comment by goodwanghan** [comment]
Oh I can see it now, never mind let me take a look.
