### ISSUE TITLE
[QUESTION] pandas DateTimeIndex not allowed?

### ISSUE THREAD

**Issue by blair-anson** [fugue-project/fugue#330]
Hi,
I setup a simple transformation with a pandas dataframe that has a DateTimeIndex but received this error
```
ValueError: pandas like datafame must have default index, but got <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
```
So I assume DateTimeIndex is not allowed?
Is there a plan to support it in the future?

**Comment by kvnkho** [comment]
Hi @blair-anson , 

Thanks for trying Fugue!

We don't support the Index concept in general because it's not performant to generalize to distributed computing backends like Spark and Dask. You can use `reset_index()` and make the datetime as a column instead of the DataFrame. I'd be happy to chat more about what you're trying to do to learn more about your use case. My contact info is in my profile.

**Comment by goodwanghan** [comment]
We also have this [blog post](https://towardsdatascience.com/why-pandas-like-interfaces-are-sub-optimal-for-distributed-computing-322dacbce43) explaining why we are not pandas-like

**Comment by goodwanghan** [comment]
Closing due to no response
